yaml
mongodb/docs-meta pull request #120
Opened 2022-07-22 14:50 UTC by kyuan-mongodb

Added the landing page for YAML content. 

The procedure directive link will need to be updated after its complete. The TOC will be added by whoever picks up the paged embedded within.

[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/yaml/reference/yaml/)

2022-07-22 14:58 UTC, mongoKart requested changes

2022-07-22 14:58 UTC, mongoKart commented on source/reference/yaml.txt
> +Before the DOP team created ``procedure`` directive, our documentation
"_the_ procedure directive"?

2022-07-22 14:58 UTC, mongoKart commented on source/reference/yaml.txt
> +   This is NOT the preffered way to write steps today. See the <TODO:
*preferred

2022-07-22 14:58 UTC, mongoKart commented on source/reference/yaml.txt
> +   procedure-directive-ref> to learn how to use the preffered way.
*preferred

2022-07-22 14:58 UTC, mongoKart commented on source/reference/yaml.txt
> +To see if the repository you're working out of uses YAML, look for the
"working out of" feels a little clunky. "Working on"? "Working from"? "Working with"?

2022-10-12 20:47 UTC, kyuan-mongodb commented
Hey @ccho-mongodb, this was for my team's skunkworks project. I was starting the yaml content towards the end, but this was supposed to be a landing page for other sub pages to cover how yaml is used in our repos. I think it's safe to close since it doesn't relate to anything else.

2022-10-12 20:56 UTC, closed without merging