(DOCSP-44517): Added new component guidelines.
mongodb/docs-meta pull request #181
Opened 2024-11-06 21:15 UTC by corryroot

# Pull Request Process

Please read the
[Style Guide Review Process](https://wiki.corp.mongodb.com/display/DE/Technical+Writer+Style+Guide+Review+Process)
wiki page.

Contributors should take the following actions:

- Request a PR review in #docs-style-guide Slack channel.
- Add the Style Guide team reps as reviewers.
- If any reviewer requests changes, address them and request another review.
- When you receive PR review approvals from all the Style Guide team reps,
  they will merge the PR and notify you of the merge in the Slack channel.

# Pull Request Description

I added the following new component guidelines:

[JIRA](https://jira.mongodb.org/browse/DOCSP-44517)

[Callouts](https://deploy-preview-181--mongodb-docs-meta.netlify.app/style-guide/style/callouts/)

[Method and Language Selectors](https://deploy-preview-181--mongodb-docs-meta.netlify.app/style-guide/style/language-selectors/)

[Collapsible Sections](https://deploy-preview-181--mongodb-docs-meta.netlify.app/style-guide/style/collapsible-sections/)

[Next Buttons](https://deploy-preview-181--mongodb-docs-meta.netlify.app/style-guide/style/next-buttons/)

[Procedures](https://deploy-preview-181--mongodb-docs-meta.netlify.app/style-guide/style/tasks/#procedures)

2024-11-06 22:59 UTC, stephmarie17 requested changes
Nice work ✨ looks great overall, just had some small comments and a question.

2024-11-06 22:59 UTC, stephmarie17 commented on source/style-guide/style/collapsible-sections.txt
> +- For the subheader, write a very short one-line descrition with a
Small typo:
```suggestion
- For the subheader, write a very short one-line description with a 
```

2024-11-06 22:59 UTC, stephmarie17 commented on source/style-guide/style/collapsible-sections.txt
> +  .. figure:: /images/collapsible-section-subheader.png
Note for this image, there is a typo in each example: Prerequisistes -> Prerequisites

2024-11-06 22:59 UTC, stephmarie17 commented on source/style-guide/style/tasks.txt
> +  .. figure:: /images/procedure-subheaders.png
[n] Inconsistent spelling in the ❌  image: Sub header -> subheader

2024-11-06 22:59 UTC, stephmarie17 commented on source/style-guide/style/language-selectors.txt
> +  .. figure:: /images/language-selector-driver-method.png
[q] I'm confused by this diagram, should a different method be highlighted in the ❌ example? Both have **Driver** selected.

2024-11-07 20:47 UTC, stephmarie17 approved these changes
LGTM except there is a remaining `Prerequisistes` typo in the example image for `Collapsible Section Anatomy` so looks like that image will need a refresh 👍

2024-11-13 15:38 UTC, jeff-allen-mongo reviewed
@corryroot thanks for this update! This PR adds a lot of helpful clarifications. I left a few comments for your consideration.

2024-11-13 19:36 UTC, sarahsimpers reviewed
Left some comments, thanks for this PR!

2024-11-18 19:51 UTC, corryroot commented on source/style-guide/style/callouts.txt
> +- Avoid nesting callouts inside tables and other elements.
@jeff-allen-mongo, I'd make a distinction between stacking and nesting. One uses a component directly after the same or similar component and the other places a component into another component.

2024-11-18 20:03 UTC, corryroot commented on source/style-guide/style/next-buttons.txt
> +      :time-required: 5
At the top of the page. I'll remove to avoid confusion.

2024-11-18 20:04 UTC, corryroot commented on source/style-guide/style/next-buttons.txt
> +- If there is no back or next page, don't add the corresponding button.
I don't think this is actually something we control, so will remove.

2024-11-18 20:05 UTC, corryroot commented on source/style-guide/style/tasks.txt
> +1. Number
@jeff-allen-mongo, we could prefix all the anatomy with "step". I think it's implied and shown.

2024-11-18 20:07 UTC, corryroot commented on source/style-guide/style/callouts.txt
> +  the callout label.
I think some of these were design-specific. So removing.

2024-11-18 20:25 UTC, corryroot commented on source/style-guide/style/next-buttons.txt
> +- Use next buttons at the top of the page only in multi-step tutorial
@lindseymoore, see the bullet that follows this one.

2024-11-18 20:26 UTC, corryroot commented on source/style-guide/style/tasks.txt
> +            third-party authentication.
@lindseymoore, the ordered lists display the same way whether you add a line break in the rST or not.

2024-11-19 21:59 UTC, lindseymoore approved these changes
Thanks for addressing my comments, LGTM!

2024-11-20 14:39 UTC, jeff-allen-mongo commented on source/style-guide/style/language-selectors.txt
> +  method.
I see. Thanks for confirming.

2024-11-20 14:39 UTC, jeff-allen-mongo commented on source/style-guide/style/tasks.txt
> +1. Number
Sounds good. We can leave as-is.

2024-11-20 15:27 UTC, sarahsimpers approved these changes
LGTM, thank you!

2024-11-20 15:28 UTC, merged